"""empty message

Revision ID: 1ce3ece69a04
Revises: 9653c873b793
Create Date: 2017-09-08 17:53:14.897557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ce3ece69a04'
down_revision = '9653c873b793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('author_name', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'author_name')
    # ### end Alembic commands ###
