"""empty message

Revision ID: 8f63d55c81ca
Revises: 1ce3ece69a04
Create Date: 2017-09-11 11:39:01.161111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8f63d55c81ca'
down_revision = '1ce3ece69a04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'author_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('author_name', mysql.VARCHAR(length=50), nullable=False))
    # ### end Alembic commands ###
